# -*- coding: utf-8 -*-
"""infer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zRQ7cBeaOf93DSsha3cl0PyyZYPxGLlb
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/BITAMIN/gen_question/requirements.txt
!pip install -r /content/drive/MyDrive/BITAMIN/gen_question/requirements.txt

!pip freeze > ../requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/BITAMIN/gen_question/src

import torch
from transformers import PreTrainedTokenizerFast, BartForConditionalGeneration

# ✅ 학습된 모델 및 토크나이저 로드
MODEL_PATH = "../saved_model/qg_supervised"  # 학습된 모델 경로
tokenizer = PreTrainedTokenizerFast.from_pretrained(MODEL_PATH)
model = BartForConditionalGeneration.from_pretrained(MODEL_PATH)
model.eval()  # 평가 모드

import re

def generate_question(context, answer):
    """
    문맥(context)과 정답(answer)을 입력하면 질문을 생성하는 함수
    """
    input_text = f"질문 생성: {answer} 문맥: {context}"
    input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to(model.device)

    # ✅ 모델 추론
    with torch.no_grad():
        outputs = model.generate(
            input_ids,
            max_length=40,  # 🔥 너무 긴 질문 방지
            num_beams=3,  # 🔥 Beam Search 크기 조정
            repetition_penalty=1.5,  # 🔥 반복 방지
            no_repeat_ngram_size=2,  # 🔥 n-gram 반복 방지
            temperature=1.0,  # 🔥 다양성 증가
            top_k=30,  # 🔥 확률 높은 단어 30개 내 선택
            top_p=0.8,  # 🔥 확률 누적 80% 내 선택
            early_stopping=True
        )

    # ✅ 생성된 질문 디코딩
    generated_question = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # ✅ `?` 이후의 이상한 문자 제거 (정규식 활용)
    clean_question = re.sub(r"\?.*", "?", generated_question).strip()

    return clean_question

# ✅ 테스트 실행
if __name__ == "__main__":
    print("🚀 질문 생성 테스트 시작!")

    test_data = [
        {
            "context": "1919년 3월 1일, 한국에서는 일본의 식민 통치에 저항하여 대규모 독립운동이 일어났다. 이 운동은 전국적으로 확산되었으며, 학생, 종교인, 노동자 등 다양한 계층이 참여하였다. 이후 일본은 강경 진압을 하였고, 수많은 사상자가 발생하였다. 이 운동은 한국의 독립운동에 중요한 계기가 되었으며, 이후 대한민국 임시정부가 수립되는 데 영향을 미쳤다.",
            "answer": "3.1 운동"
        },
        {
            "context": "상대성이론은 시간과 공간이 절대적이지 않으며, 관찰자의 속도에 따라 다르게 측정될 수 있음을 설명하는 이론이다. 이 이론은 특수 상대성이론과 일반 상대성이론으로 나뉘며, 특수 상대성이론에서는 빛의 속도가 모든 관찰자에게 일정하다는 원리를 제시한다. 일반 상대성이론에서는 중력이 시공간을 휘게 한다는 개념을 도입하였다.",
            "answer": "상대성이론"
        },
        {
            "context": "수학에서 피타고라스 정리는 직각삼각형에서 빗변의 길이의 제곱이 나머지 두 변의 제곱의 합과 같다는 것을 의미한다. 이는 a² + b² = c²로 표현되며, 고대 그리스 수학자인 피타고라스에 의해 정립되었다. 이 정리는 기하학뿐만 아니라 다양한 과학 및 공학 분야에서 널리 활용된다.",
            "answer": "피타고라스 정리"
        },
        {
            "context": "대공황은 1929년 미국에서 시작된 경제 위기로, 전 세계적으로 심각한 영향을 미쳤다. 주식 시장이 붕괴되면서 많은 기업이 파산하고 실업률이 급격히 상승하였다. 이에 따라 정부는 뉴딜 정책을 시행하여 경제 회복을 시도하였으며, 공공사업을 확대하고 금융 개혁을 단행하였다.",
            "answer": "대공황"
        },
        {
            "context": "모나리자는 레오나르도 다 빈치가 그린 대표적인 초상화로, 16세기 이탈리아 르네상스 시대에 제작되었다. 이 작품은 그녀의 신비로운 미소와 독특한 분위기로 유명하며, 현재 프랑스 파리의 루브르 박물관에 전시되어 있다.",
            "answer": "모나리자"
        },
        {
            "context": "진화론은 생물 종이 자연선택을 통해 점진적으로 변화한다는 개념을 설명하는 이론이다. 이 이론은 찰스 다윈이 '종의 기원'에서 제시하였으며, 자연 환경에 적응한 개체가 생존하여 유전 형질을 다음 세대에 전달한다는 개념을 포함한다.",
            "answer": "진화론"
        },
        {
            "context": "중력은 모든 물체가 서로를 끌어당기는 힘으로, 아이작 뉴턴이 만유인력의 법칙을 통해 설명하였다. 후에 아인슈타인은 일반 상대성이론을 통해 중력이 시공간의 곡률로 인해 발생한다고 보완하였다. 이 원리는 행성의 공전, 조수 간만의 차 등 다양한 현상을 설명하는 데 사용된다.",
            "answer": "중력"
        },
        {
            "context": "명도는 색의 밝고 어두운 정도를 나타내는 개념으로, 색채학에서 중요한 요소 중 하나이다. 색의 명도가 높을수록 밝고, 낮을수록 어둡게 보이며, 흰색은 가장 높은 명도를, 검은색은 가장 낮은 명도를 가진다.",
            "answer": "명도"
        },
        {
            "context": "플라톤은 고대 그리스 철학자로, 이데아론을 주장하였다. 그는 감각적으로 인식할 수 있는 세계는 불완전하며, 진정한 실재는 이데아의 세계에 존재한다고 보았다. 그의 철학은 이후 서양 철학에 큰 영향을 미쳤으며, '국가'와 같은 저서를 통해 이상적인 사회에 대한 논의를 전개하였다.",
            "answer": "플라톤"
        },
        {
            "context": "해양 생태계는 다양한 생물들이 서로 상호작용하며 균형을 이루는 환경이다. 이 생태계는 플랑크톤, 어류, 해양 포유류 등으로 구성되며, 해양 오염이나 기후 변화의 영향을 받을 수 있다. 특히 산호초는 해양 생태계의 중요한 부분으로, 다양한 해양 생물의 서식지 역할을 한다.",
            "answer": "해양 생태계"
        },
        {
            "context": "해양 생태계는 다양한 생물들이 서로 상호작용하며 균형을 이루는 환경이다. 이 생태계는 플랑크톤, 어류, 해양 포유류 등으로 구성되며, 해양 오염이나 기후 변화의 영향을 받을 수 있다. 특히 산호초는 해양 생태계의 중요한 부분으로, 다양한 해양 생물의 서식지 역할을 한다.",
            "answer": "박정원"
        },
        {
            "context": "조선왕조는 1392년 이성계가 건국한 왕조로, 1897년 대한제국으로 바뀌기 전까지 500년 넘게 한반도를 지배하였다. 조선은 유교를 국교로 삼았으며, 성리학을 중심으로 한 학문과 교육이 발전하였다. 세종대왕은 한글을 창제하여 한국어의 표기 체계를 정립하였으며, 과학기술과 천문학을 발전시키는 데에도 기여하였다. 이후 임진왜란과 병자호란을 거치며 조선은 국방력을 강화하고 대외 관계를 조정하는 등 변화하는 국제 정세에 적응해 나갔다. 19세기 말 개항과 함께 서구 열강과의 접촉이 늘어나며 정치적, 사회적 혼란이 가중되었고, 결국 대한제국이 수립되면서 조선은 막을 내렸다.",
            "answer": "세종대왕"
        },
        {
            "context": "광속은 진공 상태에서 약 299,792,458m/s로, 이는 우주의 기본적인 상수 중 하나로 간주된다. 아인슈타인의 특수 상대성이론에 따르면, 광속은 모든 관찰자에게 동일하게 측정되며, 물질이 광속을 초과하는 것은 불가능하다. 또한, 광속의 불변성은 시간과 공간이 절대적이지 않다는 것을 의미하며, 이는 시간 지연과 길이 수축 같은 효과를 설명하는 데 사용된다.",
            "answer": "광속"
        },
        {
            "context": "삼권분립은 정부의 권력을 입법, 행정, 사법으로 나누어 권력의 집중을 방지하고 균형을 유지하기 위한 원칙이다. 이 개념은 프랑스의 정치 철학자 몽테스키외에 의해 체계적으로 정리되었으며, 현대 민주주의 국가들의 헌법에 큰 영향을 미쳤다. 삼권분립의 원칙에 따라 입법부는 법을 만들고, 행정부는 이를 집행하며, 사법부는 법을 해석하고 적용하는 역할을 한다. 이러한 구조는 권력 남용을 방지하고 국민의 자유와 권리를 보호하는 데 기여한다.",
            "answer": "삼권분립"
        },
        {
            "context": "DNA는 생물의 유전 정보를 저장하는 분자로, 이중 나선 구조를 이루고 있다. 이 구조는 제임스 왓슨과 프랜시스 크릭에 의해 밝혀졌으며, 유전자의 복제와 단백질 합성 과정에서 중요한 역할을 한다. DNA의 염기 서열은 아데닌(A), 티민(T), 구아닌(G), 사이토신(C)으로 구성되어 있으며, 상보적 염기쌍을 통해 결합한다. 최근에는 유전자 편집 기술인 CRISPR-Cas9이 개발되면서 DNA를 정밀하게 조작하는 것이 가능해졌다.",
            "answer": "DNA"
        }
    ]

    for example in test_data:
        test_context = example["context"]
        test_answer = example["answer"]
        generated_question = generate_question(test_context, test_answer)

        print("\n🎯 Context:", test_context)
        print("✅ Generated Question:", generated_question)
        print("📝 Answer:", test_answer)
        print("-" * 80)

    print("🚀 질문 생성 테스트 완료!")

